### ISSUE TITLE
graph node cannot be named "graph" or "node"

### ISSUE THREAD

**Issue by iamaziz** [pydot/pydot#111]
If a node in the graph named **`graph`** or **`node`**, `write_png()` function produces this error:

``` python
>>> import pydot
Couldn't import dot_parser, loading of dot files will not be possible.
>>> g = pydot.Dot()
>>> e = pydot.Edge('node', 'graph')
>>> g.add_edge(e)
>>> g.write_png('BUG.png')
Warning: /var/folders/_8/_99twmsd4zg5_09q7wm2y8jm0000gn/T/tmpdWTyp8: syntax error in line 2 near '->'

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pydot.py", line 1602, in <lambda>
    lambda path, f=frmt, prog=self.prog : self.write(path, format=f, prog=prog))
  File "/Library/Python/2.7/site-packages/pydot.py", line 1696, in write
    dot_fd.write(self.create(prog, format))
TypeError: must be string or buffer, not list
```

**Comment by johnyf** [comment]
This is not a `pydot` issue, but due to the [grammar of the `dot` language](http://web.mit.edu/spin_v4.2.5/share/graphviz/doc/html/info/lang.html) that GraphViz reads as input. The words `node` and `graph` cannot be used as node names, because the resulting `dot` code is:

```python
>>> g.to_string()
'digraph G {\nnode -> graph;\n}\n'
```

The only way to avoid this would be to rename nodes if their identifiers are `dot` keywords. This is implicit and would come as a surprise. Instead, the node can be named differently, and a label defined:

```python
n0 = pydot.Node('node_', label='"node"')
n1 = pydot.Node('graph_', label='graph")
e = pydot.Edge(n0, n1)
g.add_node(n0)
g.add_node(n1)
g.add_edge(e)
>>> g.to_string()
 'digraph G {\nnode_ -> graph_;\ngraph_ [label="graph"];\nnode_ [label="node"];\n}\n'
```

Note that, currently, [the user needs to quote](https://github.com/erocarrera/pydot/blob/ebfd155d60a6000fedb2169c0d963ed5acfcf0e1/pydot.py#L162) the label, otherwise the same error will result. This is because the function [`quote_if_necessary`](https://github.com/erocarrera/pydot/blob/ebfd155d60a6000fedb2169c0d963ed5acfcf0e1/pydot.py#L186) is used at many places.

In principle, quoting only strings that are label attribute values in case they are `dot` keywords should allow unquoted input from a user, i.e., `label='graph'`.

**Comment by ankostis** [comment]
Actually not even a `label` can be `graph` unquoted.
For instance:
```bash
$ echo 'digraph G { label="graph"; }' | dot
digraph G {
        graph [bb="0,0,47,23",
                label="graph",
...
}
```
But this brakes:
```bash
$  echo 'digraph G { label=graph; }' | dot
Error: t.dot: syntax error in line 1 near 'graph'
```

It seems that tis fields is not auto-quoted.
Should i open another bug?

**Comment by ankostis** [comment]
At least ``needs_quote()` should return `None` if it is a keyword.
Technically the response it is still falsy, but the use can make informed decisions.
