### ISSUE TITLE
How to add node and edge attributes

### ISSUE THREAD

**Issue by parthi2929** [pydot/pydot#175]
Hi

Is there a way to add node and edge attributes. Not successful via networkx. Does pydot give an option?

Below is the code, with not working section commented. 
```
#  NETWORX TO PYDOT TO GRAPHVIZ MODULE
P = nx.nx_pydot.to_pydot(G)

# before sending to neato, fix the pos values
# 1. A [pos="(21.31227, 46.18656)"]; should become A [pos="21.31227, 46.18656!"];
P1 = str(P).replace('"(', '"').replace(')"','!"')
print(P1)
M = Source(P1, engine='neato',format='png')

# NOT WORKING START #-------------------
# M.attr(overlap='compress')
# M.attr(sep='3')
# M.attr('edge', fontsize='9', color='grey', fontcolor='#7c7c7c')
# M.attr('node', shape='box', width='0.1', height='0.1', style='filled', fontname="Arial", fontsize='10', fixedsize='true', color="#666666")
# NOT WORKING END #---------------------

M.render('test1', view=True)  

```

**Comment by peternowee** [comment]
For posterity's sake, showing some different ways:

```python3
import pydot
G = pydot.Graph('G', overlap='compress')
G.set_sep('3')
G.set_edge_defaults(fontsize='9', color='grey', fontcolor='#7c7c7c')
G.set_node_defaults(shape='box', width='0.1', height='0.1', style='filled', fontname="Arial", fontsize='10', fixedsize='true', color="#666666")
N = pydot.Node('N')
G.add_node(N)
O = pydot.Node('O', width='0.5')
O.set_height('0.8')
G.add_node(O)
print(G)
```

Output:

```dot
digraph G {
overlap=compress;
sep=3;
edge [color=grey, fontcolor="#7c7c7c", fontsize=9];
node [color="#666666", fixedsize=true, fontname=Arial, fontsize=10, height="0.1", shape=box, style=filled, width="0.1"];
N;
O [height="0.8", width="0.5"];
}
```

Alternatively, you can access `G.obj_dict['attributes']` directly, but I assume that is discouraged.

**Comment by laowantong** [comment]
Thanks! Note however that setting the node defaults (for instance) must be done before they are created. Otherwise, the line:
```
node [color="#666666", fixedsize=true, fontname=Arial, fontsize=10, height="0.1", shape=box, style=filled, width="0.1"];
```
... is appended after the nodes have been listed, and has no effect on the output.

**Comment by peternowee** [comment]
Hi @laowantong,

> Note however that setting the node defaults (for instance) must be done before they are created.

Yes, you are right, thanks for pointing that out. See https://github.com/pydot/pydot/issues/80#issuecomment-356370791 as well. The docstring for `set_node_defaults()` documents this behavior since pydot 1.4.2:

```python
    def set_node_defaults(self, **attrs):
        """Define default node attributes.

        These attributes only apply to nodes added to the graph after
        calling this method.
        """
```

If we ever release full documentation for pydot (see pydot/pydot#130), then I assume that remark in the docstring will not be overlooked when documenting the `set_..._defaults` methods. For the basic examples currently in the README, the whole subject of setting defaults is already a bit too advanced, I think, let alone the finer art of how to order them.

> The following workaround moves the declarations to the second line of the string representation:
> 
> ```python
> import re
> string = re.sub(r"(?m)(.+\n)((?:.*\n)*?)^((?:(?:node|edge|graph) \[.+\n)+)", r"\1\3\2", graph.to_string())
> ```

Thanks for sharing, hopefully it will help someone. However, I think manual DOT string editing with regex substring replacement goes a bit beyond the purpose of pydot, so I doubt if this workaround should be included in the pydot documentation. This workaround is not needed when the user just sets the defaults before creating the nodes, right? Anyway, if people are helped by it, I hope they can leave some comments below and then maybe we can see if we document it as a side note or tip or something.

Thanks, all the best!

**Comment by peternowee** [comment]
Hmm, yes, I see. I do not know NetworkX that well, but looking at the source code, it does seem to try to set some defaults at the start of the export:

```python3
    name = N.name
    graph_defaults = N.graph.get("graph", {})
    if name == "":
        P = pydot.Dot("", graph_type=graph_type, strict=strict, **graph_defaults)
    else:
        P = pydot.Dot(
            f'"{name}"', graph_type=graph_type, strict=strict, **graph_defaults
        )
    try:
        P.set_node_defaults(**N.graph["node"])
    except KeyError:
        pass
    try:
        P.set_edge_defaults(**N.graph["edge"])
    except KeyError:
        pass
```
From: https://github.com/networkx/networkx/blob/networkx-2.6.3/networkx/drawing/nx_pydot.py#L197-L212

Where `N` is the NetworkX graph, so if we can set `N.graph["graph"]`, `N.graph["node"]`, and `N.graph["edge"]` before calling `nx.drawing.nx_pydot.to_pydot()`, NetworkX should include them as defaults in the pydot graph. For example:

```python3
import networkx as nx
import pydot
G = nx.Graph()
G.graph["node"] = {"style": "filled", "fillcolor": "blue"}
G.add_node("a")
graph = nx.drawing.nx_pydot.to_pydot(G)
print(graph)
```

Output:
```dot
strict graph  {
node [fillcolor=blue, style=filled];
a;
}
```

This is what you mean, right?

**Comment by laowantong** [comment]
Genius! Yes, it seems to be THE clean solution. This is an undocumented feature of Networkx. Thank you for having taken the time to find and explain it. My bad, I should have read the code!

**Comment by peternowee** [comment]
No problem, good luck!
