### ISSUE TITLE
bugs in windows and anaconda env

### ISSUE THREAD

**Issue by ChenZhongPu** [pydot/pydot#210]
If it is windows and it is anaconda, the default executable extension is bat, not exe. However, the installation of graphaviz do not have any bat!

More information can be found at [medium](https://medium.com/@chenzhongpu/pydot-bugs-in-anaconda-c4bb76d9231a).

**Comment by ChenZhongPu** [comment]
BTW, it works well if `pydot` is installed via `conda`. The bugs shows when it is installed via `pip` in a anoconda env.

**Comment by peternowee** [comment]
I don't have the solution, but just wanted to share some information related to this issue that I came across while investigating another issue:

- `pydot`'s use of the `.bat` extension for Graphviz on Anaconda on Windows was mostly discussed in pydot/pydot-ng#52 by @prmtl and the ever eloquent @leycec. It mentions some reasons for why "Python users on Windows typically leverage `conda` rather than `pip`", so check it out.
- `pydot-ng` was a fork of `pydot`, but (as can be seen later on in that same pydot/pydot-ng#52), the `pydot` repository was transferred to the same maintainer as `pydot-ng` (@prmtl). He then archived `pydot-ng` and added parts of the `.bat`-code discussed in pydot/pydot-ng#52 to `pydot/pydot` instead (pydot/pydot@8c55fe56).
-  That commit message links to [the responsible 'upstream' code in conda-forge/graphviz-feedstock](https://github.com/conda-forge/graphviz-feedstock/blob/24a27a82edc23ea0581f9ee5b2c757fba66907b1/recipe/bld.bat#L26). Later, an issue was created upstream asking for a better solution than `.bat` files: conda-forge/graphviz-feedstock#34. That issue also has some links to other projects confronted with the same problem, so there may be some inspiration for a solution in there as well.

Hope this helps, good luck!

**Comment by peternowee** [comment]
Duplicate of issue pydot/pydot#205 _(Added Graphviz too Path but pydot cannot find dot excuable correctly)_, by the way.

**Comment by peternowee** [comment]
Closing as a duplicate of pydot/pydot#205. Thank you for reporting.
