### ISSUE TITLE
Arch packaging of pydot (Unable to install python2-pydot)

### ISSUE THREAD

**Issue by Joe23232** [pydot/pydot#225]
I need to install `ros-kinetic-desktop-full` on my Arch-based system and I used this command `yay -Sy ros-kinetic-desktop-full`. I was given a bunch of options as to what packages do I want to install and I left everything at default. [Check out this other post I have made for the full details](https://answers.ros.org/question/346294/how-to-install-ros-on-arch/)

So then I get an error message:

```
==> Error: Could not find all required packages:
    python2-pydot (Wanted by: ros-kinetic-desktop-full -> ros-kinetic-simulators -> ros-kinetic-rqt-robot-plugins -> ros-kinetic-rqt-tf-tree -> ros-kinetic-qt-dotgraph)
```
So then I tried to install `python2-pydot` but it cannot find `python2-pydot`. Does anyone know how do I install this dependency?

**Comment by peternowee** [comment]
I am not an Arch user, but it seems that the Arch package `ros-kinetic-qt-dotgraph` depends on a package `python2-pydot` that is no longer in the Arch repository (AUR). It seems that `pydot` is currently not packaged in AUR at all, although [some fork are](https://aur.archlinux.org/packages/?K=pydot).

Normally, you would first ask the `ros-kinetic-qt-dotgraph` maintainer mentioned in the [package details](https://aur.archlinux.org/packages/ros-kinetic-qt-dotgraph/), though I see his last activity was in 2017. If you cannot reach him, I guess you could flag the package as out-of-date (on the right side of that page).

From your [other post](https://answers.ros.org/question/346294/how-to-install-ros-on-arch/) I notice that your university asks Ubuntu-users to add a ros.org-hosted repository to their sources-list. It seems ROS hosts its own Ubuntu packages there, and your university prefers that you use those instead of packages maintained by the Linux distribution itself. I get the impression that ROS will officially [only support Ubuntu](https://wiki.ros.org/Distributions/ReleasePolicy), although other installation options are listed on the [ROS Installation Options wiki-page](https://wiki.ros.org/ROS/Installation) for other options, like installation from source.

If you still really want to install the `ros-kinetic-*` packages from AUR, you need to:
- Install `pydot` or a derivative, either:
  - Install one of [the pydot-forks currently in AUR](https://aur.archlinux.org/packages/?K=pydot), or
  - Install `pydot` [through `pip` or manually](https://github.com/pydot/pydot/#INSTALLATION)
- Somehow force the installation of the `ros-kinetic-qt-dotgraph` package, ignoring the dependency on `python2-pydot`. Possibly an option for `yay` or `pacman`, check the documentation or Arch support.
- Maybe you need to point the ROS program to the correct `pydot` location. Setting the `PYTHONPATH` environment variable might help with that.

If you succeed at all that, you might as well consider packaging `pydot` for Arch again. :)

**Comment by peternowee** [comment]
Packaging of pydot for a specific distribution, such as Arch in this case, is normally initiated at the distribution level, so I will close this issue here in the "upstream" issue tracker for now. If there are new developments or specific issues that prevent such packaging, feel free to reopen this issue or create a new issue.
