### ISSUE TITLE
pydot png resolution issue

### ISSUE THREAD

**Issue by zzaebok** [pydot/pydot#226]
Hi, I used 'netwokx' package to make a directed graph.
And I hoped to visualize it through pydot.
When I tried it with a small graph, I could get a high quality png image.
So I tried visualization of my own graph but got a bad quality image through it.
The number of nodes are around 10k.

```python
from networkx.drawing.nx_pydot import to_pydot

graph = nx.DiGraph()
#
# adding nodes and edges here anyway
#
d1 = to_pydot(graph)
d1.set_rankdir("LR")
d1.set_margin(1)
d1.write_png('ppp.png')
```
I tried code above and the below image is the result.
What can I do to get a better resolution image??

Thanks.

![image](https://user-images.githubusercontent.com/44357534/76934974-8db63a80-6933-11ea-82ae-c1b623fadaa5.png)

**Comment by zzaebok** [comment]
The cause of the problem was its extension. I don't know how it exactly works but found that I can resolve it by changing the method to 'write_svg'. Maybe the way it handles png format cannot handle way too large file.

**Comment by peternowee** [comment]
For posterity's sake, an answer to the original question about the resolution of the PNG export:

Pydot uses Graphviz to layout the graphs, so you can look at the [Graphviz documentation](https://www.graphviz.org/documentation/) for ways to control the layout. Here, I will use the graph attribute [`size`](https://graphviz.gitlab.io/_pages/doc/info/attrs.html#d:size) to control the resolution of the export PNG file. Other relevant attributes could be [`dpi`](https://graphviz.gitlab.io/_pages/doc/info/attrs.html#d:dpi) and [`ratio`](https://graphviz.gitlab.io/_pages/doc/info/attrs.html#d:ratio). Alternatively, the Graphviz FAQ on [how to make layouts larger](https://www.graphviz.org/faq/#FaqLarger) suggests changing fonts, distances and line widths. Finally, refer to the documentation on [Graphviz Command-line Usage](https://graphviz.gitlab.io/_pages/doc/info/command.html) and [The DOT Language](https://www.graphviz.org/doc/info/lang.html) on how attributes are set there, because the methods of setting attributes from pydot and NetworkX are a reflection of that.

Below examples are for the `size` attribute. Note that the unit for `size` is inches and the default number of dots per inch (dpi) is 96, so 30 inches * 96 dpi = 2880 pixels. In my setup, all the examples below result in an image with a width of 2880 pixels. The [`dot` man-page](https://graphviz.gitlab.io/_pages/pdf/dot.1.pdf) says the value of `size` needs to be wrapped in double quotes, but as we will see below, that is not always true.

Versions used: Debian 10.3 GNU/Linux, Graphviz 2.40.1, python 3.7.3, pydot 1.4.1, NetworkX 2.4.

##### 1. In the DOT-file
```dot
graph {
    size="30,30!";
    a [label=<hi>];
}
```

##### 2. Using Graphviz directly from the command line, without pydot or NetworkX
```
$ dot -Tpng -Gsize="30,30!" a.dot >a.png
```
Note that your shell may actually interpret the double quotes. With bash, for example, what actually gets executed is this:
```
dot -Tpng -Gsize=30,30! a.dot >a.png
```
(When I do pass actual double quotes, e.g. in bash using `-Gsize=\"30,30!\"` or `$'-Gsize=\"30,30!\"'`, Graphviz `dot` ignores the entire argument.)

##### 3. Using pydot to supply a Graphviz command-line parameter
```python
import pydot
G = pydot.graph_from_dot_data("graph { a [label=<hi>]; }")
G[0].write_png("a.png", prog=['dot','-Gsize=30,30!'])
```
(Again, when I pass double quotes (`['dot','-Gsize="30,30!"']`), this results in Graphviz `dot` ignoring the argument, so I leave them out.)

##### 4. Using pydot, adding the attribute to the pydot Graph object
```python
import pydot
G = pydot.graph_from_dot_data("graph { a [label=<hi>]; }")
G[0].set_size("30,30!")
G[0].write_png("a.png")
```

##### 5. Using NetworkX, adding the attribute to the pydot Graph object
```python
import networkx
from networkx.drawing.nx_pydot import to_pydot
graph = networkx.Graph()
graph.add_node("a", label="<hi>")
d1 = to_pydot(graph)
d1.set_size("30,30!")
d1.write_png("a.png")
```
