### ISSUE TITLE
Need a way to make edge lengths the same. 

### ISSUE THREAD

**Issue by angelotc** [pydot/pydot#234]
![image](https://user-images.githubusercontent.com/26128248/90058169-fddca880-dca6-11ea-9c81-e18ba86353f6.png)
Would be cool if there was a way to make all edges the same pixel length.

**Comment by peternowee** [comment]
Hi @angelotc, thanks for your question, but I think this is first a question for Graphviz, not pydot. Pydot is just an interface to Graphviz. See [Graphviz documentation](https://www.graphviz.org/documentation/), on [attributes](https://www.graphviz.org/doc/info/attrs.html) for examples. Also, questions like these are better asked on a Q&A sites like StackOverflow (tag `graphviz`) or forums rather than on an issue tracker.

Still, I had a look at https://github.com/angelotc/Ford-Fulkerson-Implementation, where your question seems to originate from.

I inspected the DOT-output it generates by inserting the following line:

```python3
            graph.write_raw(f'{i}.raw.dot')
```

This results in the following DOT-output:

```dot
digraph G {
rankdir=LR;
1 -> 2  [color=blue, fontsize="10.0", label=9, labelfontcolor="#009933"];
1 -> 3  [color=blue, fontsize="10.0", label=7, labelfontcolor="#009933"];
2 -> 3  [color=blue, fontsize="10.0", label=8, labelfontcolor="#009933"];
3 -> 2  [color=blue, fontsize="10.0", label=3, labelfontcolor="#009933"];
2 -> 4  [color=blue, fontsize="10.0", label=5, labelfontcolor="#009933"];
3 -> 4  [color=blue, fontsize="10.0", label=4, labelfontcolor="#009933"];
3 -> 5  [color=blue, fontsize="10.0", label=2, labelfontcolor="#009933"];
5 -> 4  [color=blue, fontsize="10.0", label=3, labelfontcolor="#009933"];
5 -> 6  [color=blue, fontsize="10.0", label=6, labelfontcolor="#009933"];
4 -> 6  [color=blue, fontsize="10.0", label=10, labelfontcolor="#009933"];
}
```

If I run that through Graphviz manually:

```sh
dot -Tpng 0.raw.dot >0.png
```

I get the same image as you posted:

![0](https://user-images.githubusercontent.com/10220583/103156957-879c9680-47ae-11eb-8bef-6662a089e6e1.png)

I guess you expect the result to look a bit more orderly, like many of the examples in https://commons.wikimedia.org/wiki/Category:Ford-Fulkerson%27s_algorithm, for example [this one by Ekreckel on Wikimedia Commons](https://commons.wikimedia.org/wiki/File:FordFulkersonAlgorithmusBeispiel1.png):

![1](https://upload.wikimedia.org/wikipedia/commons/0/02/FordFulkersonAlgorithmusBeispiel1.png)

Note, though, that not all edges can be the same length. The diagonal edge between 2 and 5 (or between 3 and 4 in your example) will always be longer than the other edges.

Anyway, if I now modify the DOT-file by adding some subgraphs with attribute `rank` at the bottom:

```dot
digraph G {
rankdir=LR;
1 -> 2  [color=blue, fontsize="10.0", label=9, labelfontcolor="#009933"];
1 -> 3  [color=blue, fontsize="10.0", label=7, labelfontcolor="#009933"];
2 -> 3  [color=blue, fontsize="10.0", label=8, labelfontcolor="#009933"];
3 -> 2  [color=blue, fontsize="10.0", label=3, labelfontcolor="#009933"];
2 -> 4  [color=blue, fontsize="10.0", label=5, labelfontcolor="#009933"];
3 -> 4  [color=blue, fontsize="10.0", label=4, labelfontcolor="#009933"];
3 -> 5  [color=blue, fontsize="10.0", label=2, labelfontcolor="#009933"];
5 -> 4  [color=blue, fontsize="10.0", label=3, labelfontcolor="#009933"];
5 -> 6  [color=blue, fontsize="10.0", label=6, labelfontcolor="#009933"];
4 -> 6  [color=blue, fontsize="10.0", label=10, labelfontcolor="#009933"];
{ rank=source 1 }
{ rank=same 2 3 }
{ rank=same 4 5 }
{ rank=sink 6 }
}
```

Then run that through Graphviz:

```sh
dot -Tpng 0-rank.raw.dot >0-rank.png
```

The image looks more like what you probably expect:

![0-rank](https://user-images.githubusercontent.com/10220583/103157165-810f1e80-47b0-11eb-89e8-76c90dad70e8.png)

To get this result from your script, use `pydot.Subgraph`. A very rudimentary example of what you can insert at the end of your script to generate the necessary subgraphs:

```python3
            subg = pydot.Subgraph(rank="source")
            subg.add_node(n_dict["1"])
            graph.add_subgraph(subg)
            
            subg = pydot.Subgraph(rank="same")
            subg.add_node(n_dict["2"])
            subg.add_node(n_dict["3"])
            graph.add_subgraph(subg)
            
            subg = pydot.Subgraph(rank="same")
            subg.add_node(n_dict["4"])
            subg.add_node(n_dict["5"])
            graph.add_subgraph(subg)
            
            subg = pydot.Subgraph(rank="sink")
            subg.add_node(n_dict["6"])
            graph.add_subgraph(subg)

            graph.write_raw(f'{i}.raw.dot')
            graph.write_png(f'{i}.png')
```

Of course, you will probably want to somehow make this less hard-coded, possibly create the subgraphs while adding the nodes and edges already, but this is just to give you an example of starting with the desired DOT-output and then working your way back to generating that desired DOT-output using pydot.

There may be other ways to tell Graphviz what layout you want. Check the Graphviz documentation mentioned at the top of this post, try it out from the command line first, then work your way back to pydot.

**Comment by angelotc** [comment]
Thank you, Peter. I wanted to make an instructional youtube video on how Ford Fulkerson worked, but have lost motivation to do so recently. I will keep this in mind when I get back into business.

**Comment by peternowee** [comment]
Yes, it's difficult to stay motivated these days, I know all about it. Hope you can keep it up.

Shall we close this issue? You can always open a new one if you find a real bug or have a feature request specifically for pydot.
