### ISSUE TITLE
1.4.2: ERROR: test_graph_pickling (__main__.TestGraphAPI)

### ISSUE THREAD

**Issue by sandrotosi** [pydot/pydot#256]
Hello,
with the newly released 1.4.2, i get this error when running the unittests:

```
ERROR: test_graph_pickling (__main__.TestGraphAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pydot-1.4.2/test/pydot_unittest.py", line 114, in test_graph_pickling
    pickle.dumps(g)
AttributeError: Can't pickle local object 'Common.create_attribute_methods.<locals>.<lambda>'
```

**Comment by peternowee** [comment]
Hi @sandrotosi, thanks for reporting. This test does not fail on plain pydot 1.4.2 as we distribute it here on GitHub and on PyPI.org, but only after applying the additional patch for the Debian package [`debian/patches/serialize-via-dill.patch`](https://salsa.debian.org/python-team/packages/pydot/-/blob/debian/1.4.2-1/debian/patches/serialize-via-dill.patch), applied since Debian pydot 1.4.1-2. The test failure was happening with Debian pydot 1.4.1-2 already, which is why [the test suite was disabled for Debian pydot 1.4.1-3](https://salsa.debian.org/python-team/packages/pydot/-/commit/6c48cee45682bfe29954d450d1ab777b3fd67768).

I reviewed that patch a few months ago in https://github.com/pydot/pydot/issues/217#issuecomment-716888903, but did not get any reply. I added another comment today with some suggested solutions: https://github.com/pydot/pydot/issues/217#issuecomment-779834485.

Hope we can move this discussion to there. Closing this issue here.
