### ISSUE TITLE
PyGraphviz vs PyDot how does one decide which one to use?

### ISSUE THREAD

**Issue by brando90** [pydot/pydot#262]
I know this might be a hard question to remain unbiased but I thought having this discussion on the web somewhere might be useful for people trying to make a decision on which library to use. But what are the cons & pros or how should one decide to use PyGraphviz vs PyDo to visualize graphs in Python? (my own bias is that I am use the dgl deep learning library)

related resources:
- python.libhunt.com/compare-pydot-vs-pygraphviz
- qr.ae/pGtb7r
- https://stackoverflow.com/questions/37353199/graphviz-vs-pygraphviz

**Comment by lkk7** [comment]
One thing is for sure: the `pygraphviz` installation process can get complicated if something goes wrong, because it involves compilation. I can see that there are a few open issues related to installation/deployment.

`pydot` is a pure Python wrapper that only depends on `pyparsing` (which is also a pure Python library). This allows for a quick and easy installation.
