### ISSUE TITLE
How do you pass a Dot object to Graph?

### ISSUE THREAD

**Issue by Veek** [pydot/pydot#266]
So I created a sample Tree - it went something like this:

```
g = pydot.Graph()
d = pydot.Dot()
l = [pydot.Node(i) for i in range(0,10)]
[d.add_node(n) for n in l]
e = [pydot.Edge(n, l[i+1]) for i,n in enumerate(l) if i<len(l)-1]
[d.add_edge(x) for x in e]
p = d.create()
fh = open('/tmp/gviz', 'w'); fh.write(p); fh.close()
````
And gv /tmp/gviz opens up my sample graph.

Note I did not use the _Graph_ object at all, ergo my question:
is the above a reasonable way to use Graphviz/pydot? What's the difference between pydot and Graphviz - I was doing the same thing in Graphviz. What's the purpose of the Graph class - why not just stick with _Dot_?

The pydoc was not helpful in this regard:  _Class representing a graph in Graphviz's dot language._ **A container for handling a dot language file.** What's the difference [note that d.create() doesn't auto create anything - it just gives you a string in whatever format]?

Therefore the title: can you pass a Dot object to Graph and perhaps do the styling in there? 

[sorry if the Q is stupid/inappropriate but I've just started Graphs - been all of two days roughly - I was looking for a specific feature - tried treelib, Graphviz and then pydot. Basically I need a way to identify a node based on a condition and make that a subtree. I've asked here: https://github.com/caesar0301/treelib/issues/182]

**Comment by peternowee** [comment]
> What's the purpose of the Graph class - why not just stick with Dot?

> What's the difference [..]?

I usually just use `pydot.Dot`. It is a subclass of `pydot.Graph`, so it can do everything a `pydot.Graph` can and on top of that it can also call Graphviz to create and export to various formats.

Not sure about the history of it all, but perhaps the classes were modeled after the components defined in [the DOT Language](https://www.graphviz.org/doc/info/lang.html), such as `pydot.Graph` for DOT's `graph`, `pydot.Edge` for DOT's `edge`, `pydot.Node` for DOT's `node`. Then perhaps to keep those classes pure, `pydot.Dot` was created to hold the pydot-specific functionality. Not sure, just speculating.

> can you pass a Dot object to Graph and perhaps do the styling in there?

Not sure about casting a `pydot.Dot` to a `pydot.Graph` or vice versa. I would just stick with `pydot.Dot`.

A `pydot.Dot` has convenience methods to take care of the `open`, `write`, `close` you are doing manually. For example, to export to the Postscript file you mentioned, you could call `d.write_ps('/tmp/gviz')`.

> note that d.create() doesn't auto create anything - it just gives you a string in whatever format

Actually, the plain `d.create()` calls Graphviz already to render your graph. The default output format for `create()` is `ps`. If you want it written to a file, use `d.write('filename.ps')` or `d.write_ps('filename.ps')`. Or if you want another output format, use something like `write_png('filename.png')`.

There are basic examples in https://github.com/pydot/pydot/blob/v1.4.2/README.md#output.

**Comment by peternowee** [comment]
> What's the difference between pydot and Graphviz

Depends on what you mean by "Graphviz". Normally, I would understand it as [Graphviz](https://graphviz.org/), the command-line tool for rendering DOT graphs, with binaries such as `dot`, `neato`, `fdp`, etc. `pydot` is a Python library that offers Python objects for you to build DOT graphs with from within Python and also it is an interface to Graphviz, meaning `pydot` will call the Graphviz binary for you to render that DOT graph. You would use `pydot` if you have your data in Python already and want to have it rendered by Graphviz directly from your Python program.

Or maybe you meant one of the alternative Python packages:
- https://pypi.org/project/graphviz/
- https://pypi.org/project/pygraphviz/
- https://pypi.org/project/graphviz-python/

I do not know them that well, so you will have to check them out yourself and see what fits you best. You can always report back if there is some specific functionality there that you cannot find in `pydot`.

**Comment by Veek** [comment]
If this was my tree, can I use a condition to get a node reference: I want to locate nodes with children greater than X and move them into a sub-tree.

In this case node '20' has 7 children/leaves
> 0
> └── 100
>     ├── 4
>     └── 20
>         ├── 28
>         ├── 77
>         ├── 80
>         ├── 83
>         ├── 84
>         ├── 87
>         │   └── 17
>         └── 98

**Comment by peternowee** [comment]
Hi @Veek I am sorry, but your questions seem more related to the problem you are trying to solve than to pydot. This is the pydot issue tracker, mainly for reporting bugs or feature requests related specifically to pydot. I do not know much about trees, treelib, etc. Pydot just offers you Python classes to build a DOT graph with and an interface to Graphviz for rendering images of that DOT graph. It seems the questions you have are more processing-related, so from before the stage where you want to start rendering. Pydot does not have methods to make calculations or do extensive selecting and filtering on elements of the DOT graph (except maybe for returning all the nodes of a specific edge or graph or something). If you want to programmatically traverse your DOT graph and do all kinds of operations on it, you would have to write that logic yourself. Pydot just offers you the methods to add and remove nodes and edges then, but you need to program the algorithm that tells Pydot what to do. Maybe you need to look for a library that can help you work with trees. Perhaps [NetworkX](https://github.com/networkx/networkx).

Sorry. If I am misunderstanding, please try to rephrase your question and keep the example minimal, but complete. For example, instead of list comprehensions just provide a short list of values.

**Comment by Veek** [comment]
thanks, I'll try NetworkX. Looking at the PyDot methods I mistakenly concluded it might be a good fit.

**Comment by peternowee** [comment]
Yeah, I don't know, maybe for a part of the job. Anyway, good luck and I will close this issue now.
