### ISSUE TITLE
Graph object cannot have name "graph" as it breaks GraphViz

### ISSUE THREAD

**Issue by Claygirl** [pydot/pydot#282]
Naming Graph "graph", eg. `graph = pydot.Dot("graph", graph_type="graph")`
leads to following Dot string:
```
graph graph {
1 [label=ROOT];
2 [label=S];
2 -- 1;
3 [label=NP];
3 -- 2;
4 [label=VP];
4 -- 2;
5 [label=DT];
5 -- 3;
6 [label=VBZ];
6 -- 4;
7 [label=NP];
7 -- 4;
8 [label=This];
8 -- 5;
9 [label=is];
9 -- 6;
10 [label=DT];
10 -- 7;
11 [label=NN];
11 -- 7;
12 [label=a];
12 -- 10;
13 [label=test];
13 -- 11;
}
```
and following GraphViz error on any interaction:
```
"dot" with args ['-Tpng', '/tmp/tmpa165fw3n'] returned code: 1

stdout, stderr:
 b''
b"Error: /tmp/tmpa165fw3n: syntax error in line 1 near 'graph'\n"
```

**Comment by Claygirl** [comment]
Obviously a very minor issue, but confusing for first-time users.

**Comment by peterhs73** [comment]
I ran into the same issue when using "subgraph" as a node name. A little digging turned out they are reserved as dot file [keywords](https://graphviz.org/doc/info/lang.html) (for anyone who comes across this PR). 

The exception message displayed if a node name is invalid:

```
"dot" with args ['-Tsvg', 'C:\\Users\\***\\AppData\\Local\\Temp\\tmplrgvkgbm'] returned code: 1

stdout, stderr:
 b''
b"Error: C:\\Users\\***\\AppData\\Local\\Temp\\tmplrgvkgbm: syntax error in line 5 near '['\r\n"
```

I think this might be too cryptic for a dot file noob like me.

**Comment by ferdnyc** [comment]
According to that grammar, ID values can _optionally_ be quoted — but since any ID **might** be a keyword, it's probably a good idea for any code generating graphs to just always quote all of them. 

`dot` can't parse the OP's graph, but it has no issues with this one:

```dot
graph "graph" {
"1" [label=ROOT];
"2" [label=S];
"2" -- "1";
"3" [label=NP];
"3" -- "2";
"4" [label=VP];
"4" -- "2";
"5" [label=DT];
"5" -- "3";
"6" [label=VBZ];
"6" -- "4";
"7" [label=NP];
"7" -- "4";
"8" [label=This];
"8" -- "5";
"9" [label=is];
"9" -- "6";
"10" [label=DT];
"10" -- "7";
"11" [label=NN];
"11" -- "7";
"12" [label=a];
"12" -- "10";
"13" [label=test];
"13" -- "11";
}
```

(It only "needs" to quote the `"graph"`, but @peterhs73 's comment shows why it's safer to just quote ALL of the IDs, even numeric ones. As the grammar says, an ID is just a string; there's no difference between `1` and `"1"` as an ID. But there _is_ a difference between `graph` or `subgraph` and `"graph"` or `"subgraph"`.)

**Comment by ferdnyc** [comment]
I just circled back around to this... there's actually a note in the pydot source about using keywords as names, specifically:

```python
# If the name is a reserved keyword it will need quotes but pydot
# can't tell when it's being used as a keyword or when it's simply
# a name. Hence the user needs to supply the quotes when an element
# would use a reserved keyword as name. This function will return
# false indicating that a keyword string, if provided as-is, won't
# need quotes.
```

...But I'm not so sure that's _entirely_ accurate.

I see its point, to an extent. When checking node names, for instance, using `graph` or `edge` or `node` as the name is how you set defaults, and it _cannot_ be quoted or it won't work. But pydot knows when it's processing node name and when it's processing a graph or subgraph name, and it _could_ quote keywords if they're used in the name of one of those entities. It just can't use the same function for everything.

I'm already working (in #339) on changes to separate out attribute quoting from identifier quoting, because it turned out those are more different than alike, and using one quoting function for everything already wasn't working.

It's not impossible that we could have a separate quoting function for node names vs. other names. `quote_node_if_necessary()` could force the keywords `graph`, `node`, and `edge` to be unquoted. But `quote_name_if_necessary()` could forcibly quote keywords. Because if any keyword is being used as an edge endpoint or a graph/subgraph name, it's invalid unless quoted.

**Comment by ferdnyc** [comment]
@lkk7 could you assign this issue to me? I don't appear to have the power to do that myself (odd), and I'd like to keep track of it.

**Comment by lkk7** [comment]
It seems that all of these naming/quoting problems boil down to one thing: Things would be fine if everything was **always**, consistently quoted whenever possible (and non-breaking for the graph)

**Comment by ferdnyc** [comment]
> It seems that all of these naming/quoting problems boil down to one thing: Things would be fine if everything was **always**, consistently quoted whenever possible (and non-breaking for the graph)

Agreed, with the addendum, "...**on output**". I still firmly believe that quoting values when _storing_ them is a mistake that only complicates things when using tools like the `get_*()` methods. There are like 3 open bugs that boil down to, "I called `g.add_node(Node("my node"))`, why does `g.get_node("my node")` return an empty list??"
