### ISSUE TITLE
graphviz 7.0.x asserts on penwidth=nan

### ISSUE THREAD

**Issue by jschueller** [pydot/pydot#293]
since 7.0.x dot asserts when penwidth=nan:

```
$ python ~/projects/pydot_bug.py 
"dot" with args ['-Tsvg', '/tmp/tmpkonw2hkw'] returned code: -6

stdout, stderr:
 b''
b'dot: arrows.c:979: arrow_length_normal: Assertion `full_length > 0 && "non-positive full length"\' failed.\n'

Traceback (most recent call last):
  File "/home/schueller/projects/pydot_bug.py", line 18, in <module>
    P.write_svg('foo.svg')
  File "/usr/lib/python3.10/site-packages/pydot.py", line 1743, in new_method
    self.write(
  File "/usr/lib/python3.10/site-packages/pydot.py", line 1828, in write
    s = self.create(prog, format, encoding=encoding)
  File "/usr/lib/python3.10/site-packages/pydot.py", line 1956, in create
    assert process.returncode == 0, (
AssertionError: "dot" with args ['-Tsvg', '/tmp/tmpkonw2hkw'] returned code: -6
```

here is the dot file:
```
digraph G {
1 -> 2;
2 -> 3;
1 -> 4  [penwidth=nan];
subgraph  {
rank=same;
3;
4;
}

}
```

here is the script:

```
import pydot

node1 = pydot.Node(1)
node2 = pydot.Node(2)
node3 = pydot.Node(3)
node4 = pydot.Node(4)

P = pydot.Dot()
P.add_edge(pydot.Edge(node1,node2))
P.add_edge(pydot.Edge(node2,node3))
P.add_edge(pydot.Edge(node1,node4, penwidth=float('nan')))

S = pydot.Subgraph(rank='same')
S.add_node(node3)
S.add_node(node4)
P.add_subgraph(S)
P.write('foo.dot')
P.write_svg('foo.svg')
```

my suggestion is to raise an exception earlier when the Edge object is created

**Comment by ferdnyc** [comment]
You know, I was going to post a slightly-modified version of your bug sample, but using `penwidth="sixteen"`, to drive home the point that pydot doesn't really _parse_ the attribute values sent to graphviz, but instead assumes the user knows what they're doing and lets `dot` sort it out.

I was _going_ to do that, but then I discovered that `dot` apparently has **no problems at all** with _this_ `.dot` code:

```dot
digraph G {
0 -> 1;
1 -> 2;
0 -> 3  [penwidth=sixteen];
subgraph  {
rank=same;
2;
3;
}

}
```

Renders just fine! No idea what it's actually _doing_ with that `sixteen`, since it's clearly not using `16` as the pen width:

![foo](https://github.com/pydot/pydot/assets/538020/4e7d44ff-8245-48b9-a598-483b37634e14)

Craziness. But perhaps that does an even better job of demonstrating _why_ pydot doesn't parse (or police, to put it differently) the attribute values it's presented with, since it can't possibly predict what will and won't be acceptable to `dot`.

**Comment by lkk7** [comment]
Right, I think this can be closed. 
The "nan" from Graphviz seems very arbitrary, you could put "null" or "nil" here and it would work fine.
Pydot shouldn't prevent the user from entering this value.

**Comment by ferdnyc** [comment]
> The "nan" from Graphviz seems very arbitrary, you could put "null" or "nil" or "whatever" here and it would work fine.

Well, that's actually because it's **not** arbitrary at all. `nan`/`NaN` is a [specific, well-defined pseudovalue](https://en.cppreference.com/w/c/numeric/math/nan) in IEEE-754 floating-point arithmetic, which both C and Python support.

And it seems graphviz is parsing it with its IEEE-754 meaning intact. The assigned attribute type of `penwidth` is `double`, and _only_ `penwidth=nan` asserts due to the constraint that `penwidth` be in the range [`0.0`,`+∞`]. IEEE-754 `NaN` does not fall within that range. (Any negative floating-point value would also assert, of course.)

So I argue that it appears very non-arbitrary. In the sense that `penwidth=nan` — specifically — fails, whereas other arbitrary things like `penwidth=null`, `penwith=nil`, and `penwidth=sixteen` parse successfully.

(What it's _doing_ with things like a bare `sixteen` or `null`, OTOH, I have no idea. It doesn't appear to be treating `null` as `0`, which would at least sort of make sense. But the edge is still visible — seemingly with its default `1.0` width — when `penwidth=null`, just like `penwidth=sixteen`. As opposed to `penwidth=0`, which makes the edge disappear.)

**Comment by ferdnyc** [comment]
> (Any negative floating-point value would also assert, of course.)

\*sigh\* Why do I even set myself up for these things?

No, actually, it wouldn't, of course not. :roll_eyes:  `penwidth=-1.0` is actually coerced into being the same as `penwidth=0.0`.

**Comment by ferdnyc** [comment]
Entertainingly, `penwidth=infinity` also asserts, but in a _completely_ different part of the code:

```console
$ echo 'digraph G {
0 -> 1;
1 -> 2;
0 -> 3 [penwidth=infinity];
subgraph { rank=same; 2; 3; }
}' | dot -Tpng |display png:-
dot: arrows.c:526: miter_point: Assertion `theta >= 0 && theta <= M_PI && "theta out of range"' failed.
```
