### ISSUE TITLE
Style is wrongly represented in the dot file for  style="rounded,filled" elements

### ISSUE THREAD

**Issue by domik82** [pydot/pydot#301]
pydot has problem with rendering dot file that would contain "rounded,filled" elements (which is supported by graphviz).
In pydot it's not encapsulated in "" sign causing rendering error.

Sample python file to reproduce it.

`import pydot

# Create the graph
graph = pydot.Dot(graph_type='digraph', fontname="Verdana", compound=True)

# Set the graph attributes
graph.set_node_defaults(shape="box", style="rounded", fontname="Verdana", margin="0.3,0.2")
graph.set_edge_defaults(fontname="Verdana")
graph.set_rankdir('LR')
graph.set_remincross(True)
graph.set_pack(True)

# Add the nodes
login = pydot.Node("Login", label="Login \n 100%", shape="doublecircle", fillcolor="cornflowerblue", color="black",
                   style="rounded,filled", fontcolor="black")
nodes = ["platformA", "platformB"]
node_attrs = [
    {"label": "platformA", "fillcolor": "gray", "fontcolor": "black", "style": "rounded,filled", "color": "black"},
    {"label": "platformB", "color": "black", "fillcolor": "seagreen", "style": "rounded,filled", "color": "black"},
]

for node, attr in zip(nodes, node_attrs):
    graph.add_node(pydot.Node(node, **attr))

# Add the subgraphs
cluster_logins = pydot.Subgraph(graph_name="cluster_logins", graph_type='digraph', color='black',
                                fillcolor='cornflowerblue', label='Logins', rank='same', style='rounded,filled')

logout = pydot.Node("logout", label="logout", fillcolor="cornflowerblue", color="black", style='rounded,filled',
                    fontcolor="black")

cluster_logout = pydot.Subgraph(graph_name="cluster_logout", graph_type='digraph', style='rounded,filled',
                                fillcolor='tan2', label='logout')

# Add the nodes to the subgraphs
cluster_logins.add_node(pydot.Node("platformA"))
cluster_logins.add_node(pydot.Node("platformB"))

cluster_logout.add_node(logout)

# Add the edges
graph.add_edge(pydot.Edge(login, "platformA", color="gray"))
graph.add_edge(pydot.Edge(login, "platformB", color="seagreen"))

# Add the subgraphs to the main graph
graph.add_subgraph(cluster_logins)
graph.add_subgraph(cluster_logout)

graph.add_edge(pydot.Edge("platformA", logout, color="seagreen"))
graph.add_edge(pydot.Edge("platformB", logout, color="seagreen"))

# Write the graph to a DOT file
graph.write_raw("reproduce.dot")
graph.add_node(login)
# Add the other nodes
`

**Comment by ferdnyc** [comment]
Mmmm, the regular expressions in `pydot.core.needs_quotes()` all seem to treat numeric values as having the characters `0-9` and `,`, implying a European comma-decimal representation:

https://github.com/pydot/pydot/blob/26bad844a66c0164403e2c73542737efede17b37/src/pydot/core.py#L288-L292

And because the comma is therefore considered permissible in unquoted values, it doesn't trigger `quote_if_necessary()` for comma-separated attribute values. Minimal reproducer:

```python
>>> import pydot
>>> n = pydot.Node(name="foo", style="rounded,filled", color="green")
>>> n.to_string()
'foo [color=green, style=rounded,filled];'
```

Clearly the `style=` value should be quoted, there. In fact, because attributes are comma-separated, so should _any_ attribute value containing a comma, even if it is the locale's decimal separator. These results seem entirely backwards:

```python3
>>> pydot.core.needs_quotes("1.234")
True
>>> pydot.core.needs_quotes("1,234")
False
```

And that wrongness is borne out in how pydot treats strings containing floating-point values:

```python3
>>> n.set(length, 1.234)
>>> n.to_string()
'foo [color=green, length=1.234, style=rounded,filled];'
>>> n.set(length, "1.234")
>>> n.to_string()
'foo [color=green, length="1.234", style=rounded,filled];'
>>> n.set(length, "1,234")
>>> n.to_string()
'foo [color=green, length=1,234, style=rounded,filled];'
```

Again, totally backwards.
