### ISSUE TITLE
Rare inconsistencies between Graphviz and Pydot

### ISSUE THREAD

**Issue by lkk7** [pydot/pydot#306]
In unit tests which compare hashes between pydot-generated and graphviz-generated images, there may (rarely) occur small inconsistencies. 

Example:
![err_clust2 dot_graphviz_18_06_03](https://github.com/pydot/pydot/assets/14022447/41279a09-5f98-4491-851a-9ba15648fd51)
instead of:
![err_clust2 dot_pydot_18_06_03](https://github.com/pydot/pydot/assets/14022447/8948e2e0-2b4a-452d-8d22-791085195d53)

They might randomly break unit tests and they need to be investigated.

More details needed. Latest PR makes failing tests like these get saved, so I'll be able to look at them when they occur.

**Comment by ferdnyc** [comment]
The outcome of the upstream investigation (see [graphviz issue 2510](https://gitlab.com/graphviz/graphviz/-/issues/2510) was that this is due to a bug in graphviz, recently fixed in [graphviz MR 3487](https://gitlab.com/graphviz/graphviz/-/merge_requests/3487).

The fixes are included in the recently-released graphviz 10.0.1, so anyone using the latest version shouldn't see these problems anymore.
