### ISSUE TITLE
fontsize needs to be quoted

### ISSUE THREAD

**Issue by iseletsk** [pydot/pydot#408]
In pydot 3.0.1 fontsize attribute is not quoted, while it should - if it is string.
Here is an example:

```
import pydot

graph = pydot.Dot("my_graph", graph_type="graph")

# Add nodes
graph.add_node(pydot.Node("A", fontsize=12))  # works
graph.add_node(pydot.Node("B", fontsize="\"12pt\""))  # works
graph.add_node(pydot.Node("C", fontsize="12pt"))  # doesn't work

# Add an edge
graph.add_edge(pydot.Edge("A", "B"))
graph.add_edge(pydot.Edge("B", "C"))

print(graph.to_string())
# Generate the SVG content
svg_content = graph.create_svg()
```

## dot file:
```
graph my_graph {
A [fontsize=12];
B [fontsize="12pt"];
C [fontsize=12pt];
A -- B;
B -- C;
}
```

Note that Node B is fine as it is created withwith graph.add_node(pydot.Node("B", fontsize="\"12pt\"")) 
but Node C is not:
graph.add_node(pydot.Node("C", fontsize="12pt"))

## Error produced:
stdout, stderr:

>  b''
> b"Warning: syntax ambiguity - badly delimited number '12p' in line 4 of /var/folders/20/2whws7mn5hdcjbrdmqbyfph00000gn/T/tmpf6psb8kv splits into two tokens\nError: /var/folders/20/2whws7mn5hdcjbrdmqbyfph00000gn/T/tmpf6psb8kv: syntax error in line 4 near ']'\n"

**Comment by ferdnyc** [comment]
Ah!! Interesting corner case that we seem to have missed, yeah.

Pydot will quote string-format attributes _unless_ they're all-alphanumeric, which sounds like it should be good enough (and covers things like `label=node1` which is fine)... but mixed-alpha/numeric strings that **start** with numerals should also be quoted.

**Comment by ferdnyc** [comment]
This is actually kind of confusing, because the type of attribute `fontsize` [is documented as "double"](https://graphviz.org/docs/attrs/fontsize/) — yet, graphviz clearly accepts a string value containing units, not just a double.

Same thing for other sizes like `height=`, which is a "double" in inches, but setting it to either `height=2` or `height="2in"` is equivalent. (And presumably, it would convert other units, like the equivalent `height="144pt"`?)

Anyway, #411 should fix it.
