### ISSUE TITLE
Coordinate of each nodes ?

### ISSUE THREAD

**Issue by cheikhnadiouf** [pydot/pydot#425]
How can we get the coordinates of each nodes ?
node.get_pos() ? not exist if not manualy typed
node.get_position() ? not exist
node.get_coordonates() ? not exist
any existing solutions since ?

**Comment by ferdnyc** [comment]
@cheikhnadiouf 

You can't, directly from Pydot; there are no coordinates to be had, as the graph hasn't been laid out yet. Coordinates are only assigned when one of the supported [layout managers](https://graphviz.org/docs/layouts/) is run on the graph data.

Generally the way to get coordinates assigned to a graph is to run it through the preferred Graphviz tool using the `dot` output mode — that generates a new graph definition, with the coordinates of each graph element inserted as attributes on that element.

The `pydot.Dot.create_dot()` method runs a Graphviz tool on the graph to generate `dot`-format output, so it's possible to import coordinate attributes into Pydot using `.create_dot()`. After creating a graph definition, you can run it through a layout engine with `.create_dot()`, then parse the results back in to Pydot using `pydot.graph_from_dot_data()`. Once you do that, you can query the `bb` attribute of the `graph` default node to get the bounding box, the `pos` attributes of each Node or Edge to get their coordinates, etc.:

```python
>>> import pydot
>>> g = pydot.Dot("G")
>>> g.add_node(pydot.Node("A", color="red"))
>>> g.add_node(pydot.Node("B", color="blue"))
>>> g.add_edge(pydot.Edge("A:se", "B:nw", style="dashed"))
>>> updated = g.create_dot()
>>> g2 = pydot.graph_from_dot_data(updated.decode("utf-8"))[0]
>>> print(g2.to_string())
digraph G {
graph [bb="0,0,84,108"];
node [label="\N"];
A [color=red, height=0.5, pos="27,90", width=0.75];
B [color=blue, height=0.5, pos="57,18", width=0.75];
A:se -> B:nw [pos="e,42,34 42,74 51.133,64.867 40.359,54.525 38.605,44.732", style=dashed];
}

>>> nodes = g2.get_nodes()
>>> for n in nodes:
...     print(f"{n.get_name()} @ {n.get("pos")}")
... 
graph @ None
node @ None
A @ "27,90"
B @ "57,18"
```

(You can also use a different layout engine by supplying a `prog=` argument to `create_dot()`, e.g. to lay out with `fdp` instead:

```python
>>> updated = g.create_dot(prog="fdp")
>>> g2 = pydot.graph_from_dot_data(updated.decode("utf-8"))[0]
>>> print(g2.to_string())
digraph G {
graph [bb="0,0,120,45"];
node [label="\N"];
A [color=red, height=0.5, pos="27.406,27.334", width=0.75];
B [color=blue, height=0.5, pos="92.862,17.555", width=0.75];
A:se -> B:nw [pos="e,77.862,32.555 42.406,12.334 42.406,12.334 57.676,21.042 68.174,27.029", style=dashed];
```

At the moment there are some "gotchas" to doing this **if** you need to access the reimported graph elements by name via calls like `get_node()`, `get_edge()`, `get_subgraph()`, etc. The formatting of the names can change in transit from Pydot->graphviz->Pydot due to Pydot's quoting and escaping rules. (see #396, #413) PR #420 (currently expected to be part of Pydot 4.0) will improve on that greatly.

But if you can use `get_nodes()` and friends and loop over the results, instead of relying on being able to look up specific nodes by name, it works fine.

**Comment by cheikhnadiouf** [comment]
Thanks, it WORKS !!
I suggest that you notify that important note and troubleshoot to get the coordinates of a node in the `README` file

**Comment by ferdnyc** [comment]
That's not a bad idea — we come so _close_ to it already, in §[Retrieve the DOT string](https://github.com/pydot/pydot/blob/a892962a2db1a71f5e0aa83cfa734720ce2bb077/README.md#retrieve-the-dot-string), we just don't really _explain_ what it means:

> * The Graphviz DOT: You can use it to check how Graphviz lays out the graph before it produces an image. It is generated by Graphviz.
> 
>     ```python
>     # As a bytes literal:
>     output_graphviz_dot = graph.create_dot()
>     # Or, save it as a DOT-file:
>     graph.write_dot("output_graphviz.dot")
>     ```

That mention just needs to be a _little_ more explicit, so people can see what it's getting at.

**Comment by cheikhnadiouf** [comment]
Thanks
