### ISSUE TITLE
How can we check  when a node is a subgraph ?

### ISSUE THREAD

**Issue by cheikhnadiouf** [pydot/pydot#429]
Given this code below:
```py
for subgraph in g.get_subgraphs():
    for node in subgraph.get_nodes():
        print(node.obj_dict["type"]) # output 'node' for all
```

The function subgraph.get_nodes() give the same value "node"  to the attribute `node.obj_dict["type"]` even when it is a subgraph so how can we check  when a node is a subgraph ?

**Comment by lkk7** [comment]
Hi @cheikhnadiouf,

Is that what you mean?
```
for subgraph in g.get_subgraphs():
    print(subgraph.obj_dict["type"]) # output: 'subgraph'
```

In your code, you're already iterating over subgraphs, but then you're iterating over all their nodes again, so you're getting nodes.
Feel free to post a more detailed example if I haven't answered your question.

**Comment by cheikhnadiouf** [comment]
Ok but the bgcolor, lwidth, lheight and margin  attributes of the subgraph are in the first node child, that is why i put a double iteration.

**Comment by ferdnyc** [comment]
@cheikhnadiouf 

Can you show either (a) the input data that's being parsed to create your graph, or (b) the output of `print(g.to_string())` for your top-level graph? We'll have a better idea of how to access the data you're looking for programmatically if we can see what it looks like, structurally.

**Comment by ferdnyc** [comment]
The way graphviz handles attributes on _graphs_ is somewhat confusing because there are two completely different syntaxes that mean the same thing. You can either set attributes on the special node named `graph`, _or_ you can set them as statements within the graph itself.

These two graph definitions mean exactly the same thing — either one will set the default style for clusters/subgraphs to `dashed`, and the default outline color to `blue`:

```dot
digraph G {
  graph [style=dashed, color=blue];
  subgraph cluster_H {
    a -> b;
  }
}
```

```dot
digraph G {
  style=dashed;
  color=blue;
  subgraph cluster_H {
    a -> b;
  }
}
```

Like I said, either will produce the exact same graph:

![out](https://github.com/user-attachments/assets/3163b832-7c98-47f1-abca-b1e8ad4057e2)

But within Pydot, the way you'd access that data is very different.

The first graph would have a node named `graph` with two attributes:

```python
>>> graph_def = g.get_node("graph")[0]
>>> graph_def.get("style")
'dashed'
>>> graph_def.get("color")
'blue'
```

The second graph would _itself_ have two attributes:

```python
>>> g.get("style")
'dashed'
>>> g.get("color")
'blue'
```

So, to know how to access those attributes, you have to know how they were initially defined.

Not sure if that's what you were asking, exactly, but I thought I'd point it out because it's one of the aspects of dealing with attributes in Pydot that can be somewhat confusing. Pydot follows Graphviz syntax as closely as possible, and there's some redundancy built into that syntax.

**Comment by ferdnyc** [comment]
Oh, just for fun, you could _also_ produce the exact same graph with either of these definitions:

```dot
digraph G {
  subgraph cluster_H {
    style=dashed;
    color=blue;
    a -> b;
  }
}
```

```dot
digraph G {
  subgraph cluster_H {
    graph [style=dashed, color=blue];
    a -> b;
  }
}
```

...The difference being that if you were to define additional clusters under G, they wouldn't inherit those defaults. Whereas they would, wither either of the first two definitions in my previous comment.

**Comment by cheikhnadiouf** [comment]
> @cheikhnadiouf
> 
> Can you show either (a) the input data that's being parsed to create your graph, or (b) the output of `print(g.to_string())` for your top-level graph? We'll have a better idea of how to access the data you're looking for programmatically if we can see what it looks like, structurally.

```dot
subgraph Group {
  label = "Group A"
  bgcolor=lightgrey
  margin=20
  NodeB
}
```

**Comment by ferdnyc** [comment]
Ah, OK, yeah. the `label`, `bgcolor`, and `margin` values are all going to be attributes of the subgraph named `Group`. So you'd reach them with:

```python3
g = <the top-level graph>
sg = g.get_subgraph("Group")[0]
sg.get("label")    # 'Group A'
sg.get("bgcolor")  # 'lightgrey'
sg.get("margin")   # 20
```

**Comment by cheikhnadiouf** [comment]
Thanks, that's the only way i found too.
